### PR TITLE
Add another DBMS option to backup&restore

### PR DESCRIPTION
**Pull request by syleeeee**
I couldn't install HedisSQL on my Mac, so I chose another tool(Mysql Workbench) and it worked fine. 
Here I add how to backup and restore the fosslight data with Mysql Workbench.

### CODE REVIEW

**Comment by soimkim** [comment]
1. It seems better to change it to a command than to write a guide for each DBMS.
2. In the data recovery section, there seems to be no need to distinguish between full recovery and data recovery. (both because fosslight db must be set.)

-> So I propose to fix it with this https://github.com/fosslight/fosslight-guide/pull/24.
(I added your corrections in the DB recovery section.)

**Comment by syleeeee** [comment]
Sounds great to me. 
But what do you think of adding a piece of information that users can try back up and restore with various DBMS?
I agree that it's unnecessary to provide the whole guide for using DBMS. Suggesting the list would be enough.

**Comment by soimkim** [comment]
Thanks for the great suggestion. 👍 
I added a list of recommended DBMSs as you suggested.

This PR will be replaced by https://github.com/fosslight/fosslight-guide/pull/24, so I will close it.

**Comment by syleeeee** [comment]
Thanks for reviewing :)

**Pull request closed without merging**
